### ISSUE TITLE
Pin messages text and banners

### ISSUE THREAD

**Issue by trelobit** [HyperLootProtocol/marketing#16]
Short and long pin texts https://docs.google.com/document/d/1T2wSo79UdOEr5-ARk84WIX-KqaAsE81KWubSpf7YRgI/edit#heading=h.x1u3ou4u66ak

- prepare a text DONE
- prepare a banners for telegram, twitter, instagram, linkedin, medium IN PROGRESS
- prepare an ANNOUNCE TEXT for the medium / facebook / discord and others IN PROGRESS

1. 5 mins of meditation with our branding kit https://github.com/HyperLootProtocol/Hyperloot-Branding
2. берешь бабу с картинки
3. ставишь на красивый фон, который не будет отвлекать внимания от текста
4. размещаешь текст (варианты для 3 баннеров), для пробы делаем пока 1 комплект

  1st slogan: Tired of Lootbox business model (Call to action: Try HyperLoot )
  2nd slogan: HyperLoot E-sport Monetization PaaS, powered by Ethereum. Zero transaction fees & Opensource. (Call to action: Participate in Airdrop)
  3rd slogan: Infrastructure Layer over ethereum.  Sidechains with masternode.  Zero transaction fees. Call to action: Participate in Airdrop)

размеры баннеров в 1 комплекте: 

Twitter (in-stream image)
Size: 1024 x 512 pixels
Format: JPG, PNG or GIF

Telegram 
The same as for Facebook

Facebook
Facebook Shared Image: 1200 X 630
Format: JPG, PNG

LinkedIn 
Post image (open graph): 1200 x 630
Format: JPG, PNG

Instagram
Instagram Photo size: photo with a width of at least 1080 pixels
Format: JPG, PNG

Medium
900px wide by any height
Format: JPG, PNG

**Comment by Kotsya** [comment]
![banner_fb-tg-ln-ig](https://user-images.githubusercontent.com/11670603/45455450-ceeede00-b6ef-11e8-9b36-aa8b440ba19c.png)
![banner_md](https://user-images.githubusercontent.com/11670603/45455451-ceeede00-b6ef-11e8-8204-a58a0c91d195.png)
![banner_tw](https://user-images.githubusercontent.com/11670603/45455452-ceeede00-b6ef-11e8-960c-6ffc6113a59f.png)

**Comment by Kotsya** [comment]
![banner_fb-tg-ln-ig](https://user-images.githubusercontent.com/11670603/45516028-8e0bcd80-b7b2-11e8-81d7-be74101ff2a4.png)
![banner_md](https://user-images.githubusercontent.com/11670603/45516029-8e0bcd80-b7b2-11e8-8374-2447dc6371fd.png)
![banner_tw](https://user-images.githubusercontent.com/11670603/45516030-8e0bcd80-b7b2-11e8-8221-1465b96ae35e.png)

**Comment by trelobit** [comment]
![hyperloot_bounty_missions](https://user-images.githubusercontent.com/30324843/45554703-a1b14580-b83f-11e8-897e-7210de5cf142.png)
